name: VDkoubei # 修改你的名称

on:
  workflow_dispatch:
  schedule:
    - cron: "29 21 * * 4" # 修改你的定时配置

jobs:
  setup:
    env:
      COMMAND: "xvfb-run python main.py claim"
      FAKE_HASH: "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') Asia/Shanghai"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 初始化环境 & 拉取项目
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        git clone https://github.com/QIN2DIM/epic-awesome-gamer.git epic
    - name: 初始化配置文件
      run: |
        cd epic/src
        echo "EPIC_EMAIL: ${{ secrets.EPIC_EMAIL }}" >> config.yaml
        echo "EPIC_PASSWORD: ${{ secrets.EPIC_PASSWORD }}" >> config.yaml
    - name: 安装依赖
      run: |
        pip install -r epic/requirements.txt
        cd epic/src/ && python main.py install
    - name: 启动项目
      run: |
        if [ -f "ctx_cookies.yaml" ];then cp ctx_cookies.yaml epic/src/database/cookies/; fi
        cd epic/src/ && ${{ env.COMMAND }}
    - name: Setup GIT user
      uses: fregante/setup-git-user@v1
    - name: 缓存身份令牌
      run: |
        cp epic/src/database/cookies/ctx_cookies.yaml .
        cp epic/src/database/logs/runtime.log .
        echo "${{ env.FAKE_HASH }}" > _token
        rm -rf epic
        git add .
        git commit -m "${{ env.FAKE_HASH }}" 
        git push -f  
